kind          = "formatter"
name          = "fprettify"
family        = "fprettify"
extensions    = [".f90", ".f95", ".f03", ".f08", ".F90", ".F95", ".f"]

[version]
argument = "--version"
regex    = 'fprettify (\d+\.\d+\.\d+)'

[run]
fix   = "-i"
check = "--check"

[settings]
indent = "--indent {value}"
config = "-c {value}"
