name          = "msvc"
kind          = "compiler"
family        = ""
homepage      = "https://visualstudio.microsoft.com/"
binary        = "cl.exe"
extensions    = [".cpp", ".cc", ".cxx", ".c++", ".c"]
supported_os  = ["windows"]
lto      = "/GL"
lto_link = "/LTCG"
cpu_ext  = ""

[version]
argument = ""
regex    = 'Version (\d+\.\d+\.\d+\.\d+)'

[sanitizer]
argument = "/fsanitize={values}"
options = ["address"]

[toolset]
cc    = "cl.exe"
cxx   = "cl.exe"
ld    = "link.exe"
ar    = "lib.exe"
strip = ""

[optimization]
"2" = "/O2"
"0" = "/Od"
"1" = "/O1"
"3" = "/Ox"
"s" = "/O1 /Os"
"z" = "/O1 /Os"

debug = "/Zi /FS"

[warnings]
normal = "/W3"
none   = "/W0"
all    = "/W4"
error  = "/W4 /WX"

[structure]
include_dir   = "/I{path}"
define        = "/D{name}"
define_value  = "/D{name}={value}"
output_obj    = "/Fo{path}"
output_bin    = "/Fe{path}"
compile_only  = "/c"
dep_file      = "/showIncludes"
dep_file_mode = "stdout"
system_lib    = "{name}.lib"
target        = ""
sysroot       = ""

[language.std]
"c++17" = "/std:c++17"
"c++20" = "/std:c++20"
"c++23" = "/std:c++latest"
"c17"   = "/std:c17"
"c11"   = "/std:c11"

[language.modules]
style = "none"

[linking.c]
abi             = "c"
compatible      = []
compile_binary  = "cl.exe"
linker          = ""
extensions      = [".c"]

[linking.cpp]
abi        = "c++"
compatible = ["c"]
linker     = ""
extensions = [".cpp", ".cc", ".cxx", ".c++"]
