name          = "opencl"
kind          = "compiler"
family        = ""
homepage      = "https://www.khronos.org/opencl/"
binary        = "clang"
extensions    = [".cl"]
requires_toolchain = ["cpp"]
lto = ""
always_flags = ["-x", "cl"]

[header]
version_arg   = "--version"
version_regex = '\b(\d+\.\d+\.\d+)\b'
passthrough        = false
passthrough_prefix = ""
sanitizer_options = []

[toolset]
ld = "clang"

[optimization]
"2" = "-O2"
"0" = "-O0"
"1" = "-O1"
"3" = "-O3"
"s" = "-Os"
"z" = "-Oz"

dbg = "-g"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra"
error  = "-Wall -Wextra -Werror"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
target       = ""
sysroot      = ""

[language.modules]
style = "none"

[language.std]
"CL3.0" = "-cl-std=CL3.0"
"CL1.0" = "-cl-std=CL1.0"
"CL1.1" = "-cl-std=CL1.1"
"CL1.2" = "-cl-std=CL1.2"
"CL2.0" = "-cl-std=CL2.0"

[linking.opencl]
abi        = "opencl"
compatible = ["c++", "c"]
linker     = "c++"
extensions = [".cl"]
