name          = "tcc"
kind          = "compiler"
family        = ""
homepage      = "https://bellard.org/tcc/"
binary        = "tcc"
extensions    = [".c"]
lto = ""

[header]
version_arg   = "-v"
version_regex = 'version (\d+\.\d+\.\d+)'
passthrough        = false
passthrough_prefix = ""
sanitizer_options = []

[toolset]
cc = "tcc"
ld = "tcc"
ar = "tcc"

[optimization]
"0" = ""
"1" = ""
"2" = ""
"3" = ""
"s" = ""
"z" = ""

dbg = "-g"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall"
error  = "-Wall -Werror"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = ""
target       = ""
sysroot      = ""

[language.modules]
style = "none"

[language.std]
"c11" = "-std=c11"
"c99" = "-std=c99"
"c17" = "-std=c17"

[linking.c]
abi             = "c"
compatible      = []
compile_binary  = "tcc"
linker          = ""
extensions      = [".c"]
