kind               = "compiler"
family             = "intel"
version_arg        = "--version"
passthrough        = false
passthrough_prefix = ""
supported_archs    = ["x86", "x86_64"]
supported_os       = ["linux", "windows"]
required_env       = ["ONEAPI_ROOT"]

[optimization]
"2" = "-O2"
"0" = "-O0"
"1" = "-O1"
"3" = "-O3"

dbg = "-g"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"

[modules]
style = "none"
