name          = "ifx"
kind          = "compiler"
family        = "intel"
homepage      = "https://www.intel.com/content/www/us/en/developer/tools/oneapi/fortran-compiler.html"
supported_archs    = ["x86", "x86_64"]
supported_os       = ["linux", "windows"]
required_env       = ["ONEAPI_ROOT"]

debug = "-g"
lto = "-ipo"
cpu_ext = "-m{name}"

extensions = [".f90", ".f95", ".f03", ".f08", ".f", ".F90"]

[version]
argument = "--version"
regex    = '(\d+\.\d+\.\d+)'

[sanitizer]
options = ["address", "undefined"]

[toolset]
ld    = "ifx"
ar    = "ar"
strip = "strip"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-cpp -MMD -MF {path}"
target       = ""
sysroot      = ""

[optimization]
"0" = "-O0"
"1" = "-O1"
"2" = "-O2"
"3" = "-O3"
"s" = "-O2"
"z" = "-O2"

[warnings]
normal = ""
none   = "-warn none"
all    = "-warn all"
error  = "-warn all -warn errors"

[language.std]
"f95"   = "-std=f95"
"f2003" = "-std=f2003"
"f2008" = "-std=f2008"
"f2018" = "-std=f2018"

[language.modules]
style = "none"

[linking.fortran]
abi        = "fortran"
compatible = ["c"]
linker     = ""
extensions = [".f90", ".f95", ".f03", ".f08", ".f", ".F90"]
