name          = "ispc"
kind          = "compiler"
family        = "intel"
homepage      = "https://ispc.github.io/"
extensions    = [".ispc"]
supported_archs    = ["x86_64", "aarch64"]
supported_os       = ["linux", "macos", "windows"]
requires_toolchain = ["cpp"]
lto = ""

[version]
argument = "--version"
regex    = '(\d+\.\d+\.\d+)'

[sanitizer]
options = []

[toolset]
ld = "ispc"

[optimization]
"2" = "-O2"
"0" = "-O0"
"1" = "-O1"
"3" = "-O3"
"s" = "-O2"
"z" = "-O2"

debug = "-g"

[warnings]
normal = ""
none   = "--woff"
all    = ""
error  = "--werror"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = ""
dep_file     = "-MMM {path}"
target       = ""
sysroot      = ""

[compiler.target_isa]
value = "--target=$(value)"

[compiler.cpu]
value = "--cpu=$(value)"

[compiler.math_lib]
default = ""
svml    = "--math-lib=svml"
system  = "--math-lib=system"

[linking.ispc]
abi        = "ispc"
compatible = ["c++", "c"]
linker     = ""
extensions = [".ispc"]
