name          = "nvc"
kind          = "compiler"
family        = "nvidia"
homepage      = "https://developer.nvidia.com/hpc-sdk"
supported_archs    = ["x86_64", "aarch64"]
supported_os       = ["linux"]

debug   = "-g"
lto     = "-Mipa"
lto_link = "-Mipa"
cpu_ext = "-m{name}"

extensions = [".c"]

[version]
argument = "--version"
regex    = '(\d+\.\d+)'

[sanitizer]
options = ["address"]

[toolset]
cc     = "nvc"
ld     = "nvc"
ar     = "ar"
ranlib = "ranlib"
strip  = "strip"
nm     = "nm"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
system_lib   = "-l{name}"
target       = ""
sysroot      = ""

[optimization]
"0"    = "-O0"
"1"    = "-O1"
"2"    = "-O2"
"3"    = "-O3"
"s"    = "-O2"
"z"    = "-O2"
"fast" = "-O4 -Mfprelaxed"

[warnings]
normal = ""
none   = ""
all    = "-Minform=warn"
error  = "-Minform=warn -Werror"

[language.std]
"c11" = "-std=c11"
"c17" = "-std=c17"
"c99" = "-std=c99"

[language.openmp]
enabled  = "-mp"
disabled = ""

[compiler.acc]
enabled  = "-acc"
disabled = ""

[compiler.target_arch]
value = "-tp=$(value)"

[linking.c]
abi            = "c"
compatible     = ["fortran"]
compile_binary = "nvc"
linker         = ""
extensions     = [".c"]
