base     = ["_llvm-base", "../languages/_cpp"]
name     = "clang++"
alias    = "clang"
homepage = "https://clang.llvm.org/"
detect   = ["clang++", "clang++-18", "clang++-17", "clang++-16", "clang++-15", "clang++-14"]
sanitizer_options = ["address", "undefined", "thread", "memory", "leak", "hwaddress", "dataflow", "cfi", "safestack"]

[toolset]
cc  = "$(binary.replace('clang++', 'clang'))"
cxx = "$(binary)"
ld  = "$(binary)"

[modules]
style         = "clang"
precompile    = "--precompile"
import_module = "-fmodule-file={name}={pcm_path}"
header_unit   = "-x c++-header"

[pch]
compile     = "-x c++-header"
use         = "-include-pch {pch_path}"
extension   = ".pch"
clangd_flag = "-include {header_path}"

[linking.objcpp]
abi        = "c++"
compatible = ["c", "objc"]
linker     = ""
extensions = [".mm"]

[compiler.lto_mode]
thin = "$(version >= '3.9' ? '-flto=thin' : '-flto')"
full = "-flto=full"
