kind          = "linter"
name          = "clang-tidy"
family        = "llvm"
binary        = "clang-tidy"
extensions    = [".cpp", ".cc", ".cxx", ".c++", ".cppm", ".c"]

[header]
version_arg   = "--version"
version_regex = 'LLVM version (\d+\.\d+\.\d+)'

[run]
check = ""
fix   = "--fix --fix-errors"

[settings]
checks = "--checks={value}"
config = "--config-file={value}"
