kind          = "linter"
name          = "clang-tidy"
family        = "llvm"
extensions    = [".cpp", ".cc", ".cxx", ".c++", ".cppm", ".c"]

[version]
argument = "--version"
regex    = 'LLVM version (\d+\.\d+\.\d+)'

[run]
check = ""
fix   = "--fix --fix-errors"

[settings]
checks = "--checks={value}"
config = "--config-file={value}"
