name          = "clang++-18"
alias         = "clang-18"
kind          = "compiler"
family        = "llvm"
homepage      = "https://clang.llvm.org/"

debug = "-g"
lto      = "-flto"
cpu_ext  = "-m{name}"

extensions = [".cpp", ".cppm", ".ixx", ".mpp", ".cc", ".cxx", ".c++", ".mm"]

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
argument = "-fsanitize={values}"
options = ["address", "undefined", "thread", "memory", "leak", "hwaddress", "dataflow", "cfi", "safestack"]

[toolset]
cc    = "clang-18"
cxx   = "clang++-18"
ld    = "clang++-18"
ar    = "ar"
strip = "strip"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
target       = "--target={triple}"
sysroot      = "--sysroot={path}"

[optimization]
"0" = "-O0"
"1" = "-O1"
"2" = "-O2"
"3" = "-O3"
"s" = "-Os"
"z" = "-Oz"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra -Wpedantic"
error  = "-Wall -Wextra -Wpedantic -Werror"

[compiler.stdlib]
"libc++"    = "-stdlib=libc++"
"libstdc++" = "-stdlib=libstdc++"
none        = "-nostdlib"

[language.std]
"c++17" = "-std=c++17"
"c++20" = "-std=c++20"
"c++23" = "-std=c++23"
"c++26" = "-std=c++26"

[language.modules]
style         = "clang"
precompile    = "--precompile"
import_module = "-fmodule-file={name}={pcm_path}"
header_unit   = "-x c++-header"

[language.pch]
compile     = "-x c++-header"
use         = "-include-pch {pch_path}"
extension   = ".pch"
clangd_flag = "-include {header_path}"

[compiler.lto_mode]
thin = "-flto=thin"
full = "-flto=full"

[linking.cpp]
abi        = "c++"
compatible = ["c", "fortran"]
linker     = ""
extensions = [".cpp", ".cppm", ".ixx", ".mpp", ".cc", ".cxx", ".c++"]

[linking.objcpp]
abi        = "c++"
compatible = ["c", "objc"]
linker     = ""
extensions = [".mm"]
