name          = "ldc2"
kind          = "compiler"
family        = "llvm"
homepage      = "https://github.com/ldc-developers/ldc"

debug = "-g"
lto      = "-flto=full"
cpu_ext  = "-m{name}"

extensions = [".d"]

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
argument = "-fsanitize={values}"
options = ["address", "thread", "memory", "undefined"]

[toolset]
ld    = "ldc2"
ar    = "ar"
strip = "strip"

[structure]
include_dir   = "-I{path}"
define        = "-d-version={name}"
define_value  = "-d-version={name}"
output        = "-of={path}"
compile_only  = "-c"
dep_file      = ""
dep_file_mode = "none"
system_lib    = "-L-l{name}"
target        = "-mtriple={triple}"
sysroot       = ""

[optimization]
"0" = "-O0"
"1" = "-O1"
"2" = "-O2"
"3" = "-O3"
"s" = "-Os"
"z" = "-Oz"

[warnings]
normal = ""
none   = ""
all    = "-wi"
error  = "-w"
[compiler.dip1000]
"false" = ""
"true"  = "-preview=dip1000"

[linking.d]
abi        = "d"
compatible = ["c"]
linker     = ""
extensions = [".d"]
