kind          = "compiler"
family        = "gnu"
version_arg   = "--version"
version_regex = '\b(\d+\.\d+\.\d+)\b'
passthrough        = false
passthrough_prefix = ""
sanitizer_options  = ["address", "undefined", "thread", "leak"]

detect = ["g++", "g++-14", "g++-13", "g++-12", "g++-11", "g++-10"]

dbg      = "-g"
lto      = "-flto"
sanitize = "-fsanitize={values}"
cpu_ext  = "-m{name}"

always_flags = ["$(arch == 'x86_64' ? '-m64' : arch == 'x86' ? '-m32' : '')"]

[toolset]
ar    = "ar"
strip = "strip"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
target       = ""
sysroot      = "--sysroot={path}"

[optimization]
"2" = "-O2"
"0" = "-O0"
"1" = "-O1"
"3" = "-O3"
"s" = "-Os"
"z" = "-Oz"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra -Wpedantic"
error  = "-Wall -Wextra -Wpedantic -Werror"

[stdlib]
"libstdc++" = ""
none        = "-nostdlib"
