name          = "aarch64-linux-gnu"
kind          = "compiler"
family        = "gnu"
homepage      = "https://gcc.gnu.org/"
supported_os  = ["linux"]

debug    = "-g"
lto      = "-flto"
lto_link = "-flto"
cpu_ext  = "-m{name}"
design   = "gcc"

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
argument = "-fsanitize={values}"
options = ["address", "undefined", "thread", "leak"]

[toolset]
cc      = "aarch64-linux-gnu-gcc"
cxx     = "aarch64-linux-gnu-g++"
ld      = "aarch64-linux-gnu-g++"
ar      = "aarch64-linux-gnu-ar"
ranlib  = "aarch64-linux-gnu-ranlib"
strip   = "aarch64-linux-gnu-strip"
nm      = "aarch64-linux-gnu-nm"
objcopy = "aarch64-linux-gnu-objcopy"
objdump = "aarch64-linux-gnu-objdump"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
system_lib   = "-l{name}"
target       = ""
sysroot      = "--sysroot={path}"

[optimization]
"0"    = "-O0"
"1"    = "-O1"
"2"    = "-O2"
"3"    = "-O3"
"g"    = "-Og"
"s"    = "-Os"
"z"    = "-Oz"
"fast" = "-Ofast"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra -Wpedantic"
error  = "-Wall -Wextra -Wpedantic -Werror"

[language.std]
"c++17"   = "-std=c++17"
"c++20"   = "-std=c++20"
"c++23"   = "-std=c++23"
"c++26"   = "-std=c++26"
"c++14"   = "-std=c++14"
"c++11"   = "-std=c++11"
"gnu++17" = "-std=gnu++17"
"gnu++20" = "-std=gnu++20"

[language.exceptions]
enabled  = "-fexceptions"
disabled = "-fno-exceptions"

[language.rtti]
enabled  = "-frtti"
disabled = "-fno-rtti"

[language.visibility]
default  = "-fvisibility=default"
hidden   = "-fvisibility=hidden"

[compiler.debug_info]
dwarf4 = "-gdwarf-4"
dwarf5 = "-gdwarf-5"
gdb    = "-ggdb3"
"1"    = "-g1"
"2"    = "-g2"
"3"    = "-g3"

[linking.cpp]
abi        = "c++"
compatible = ["c", "fortran"]
linker     = ""
extensions = [".cpp", ".cppm", ".ixx", ".mpp", ".cc", ".cxx", ".c++"]
