name          = "g++"
alias         = "gcc"
kind          = "compiler"
family        = "gnu"
homepage      = "https://gcc.gnu.org/"

supported_archs = ["x86_64", "x86", "aarch64", "armv7", "riscv64", "powerpc64le", "s390x"]
supported_os    = ["linux", "macos", "windows"]

debug    = "-g"
lto      = "-flto"
lto_link = "-flto"
cpu_ext  = "-m{name}"
design   = "gcc"

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
argument = "-fsanitize={values}"
options = ["address", "undefined", "thread", "leak"]

[arch_flags]
x86_64      = "-m64"
x86         = "-m32"
aarch64     = ""
armv7       = "-mthumb"
riscv64     = ""
powerpc64le = ""

[toolset]
cc      = "$(binary.replace('g++', 'gcc'))"
cxx     = "$(binary)"
ld      = "$(binary)"
ar      = "ar"
ranlib  = "ranlib"
strip   = "strip"
nm      = "nm"
objcopy = "objcopy"
objdump = "objdump"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
system_lib   = "-l{name}"
target       = ""
sysroot      = "--sysroot={path}"

[optimization]
"0"    = "-O0"
"1"    = "-O1"
"2"    = "-O2"
"3"    = "-O3"
"g"    = "-Og"
"s"    = "-Os"
"z"    = "-Oz"
"fast" = "-Ofast"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra -Wpedantic"
error  = "-Wall -Wextra -Wpedantic -Werror"

[language.std]
"c++17"   = "-std=c++17"
"c++20"   = "-std=c++20"
"c++23"   = "-std=c++23"
"c++26"   = "-std=c++26"
"c++14"   = "-std=c++14"
"c++11"   = "-std=c++11"
"gnu++17" = "-std=gnu++17"
"gnu++20" = "-std=gnu++20"
"gnu++23" = "-std=gnu++23"

[language.exceptions]
enabled  = "-fexceptions"
disabled = "-fno-exceptions"

[language.rtti]
enabled  = "-frtti"
disabled = "-fno-rtti"

[language.visibility]
default   = "-fvisibility=default"
hidden    = "-fvisibility=hidden"
internal  = "-fvisibility=internal"
protected = "-fvisibility=protected"

[language.stack_protector]
strong = "-fstack-protector-strong"
all    = "-fstack-protector-all"
none   = "-fno-stack-protector"

[compiler.debug_info]
dwarf4 = "-gdwarf-4"
dwarf5 = "-gdwarf-5"
gdb    = "-ggdb3"
"1"    = "-g1"
"2"    = "-g2"
"3"    = "-g3"

[compiler.lto_mode]
auto      = "-flto=auto"
jobserver = "-flto=jobserver"

[linking.cpp]
abi        = "c++"
compatible = ["c", "fortran"]
linker     = ""
extensions = [".cpp", ".cppm", ".ixx", ".mpp", ".cc", ".cxx", ".c++"]
