name               = "gas"
kind               = "compiler"
family             = ""
homepage           = "https://www.gnu.org/software/binutils/"
binary             = "as"
extensions         = [".s", ".S"]
requires_toolchain = ["c"]

always_flags = []

[version]
argument = "--version"
regex    = 'GNU assembler (?:\([^)]+\) )?(\d+\.\d+(?:\.\d+)?)'

[passthrough]
enabled = false
prefix  = ""

[sanitizer]
options = []

[optimization]
"0" = ""
"1" = ""
"2" = ""
"3" = ""
"s" = ""
"z" = ""

[warnings]
normal = ""
none   = "--no-warn"
all    = "--warn"
error  = "--warn --fatal-warnings"

debug = "--gdwarf-2"
lto = ""

[structure]
include_dir  = "-I{path}"
define       = "--defsym {name}=1"
define_value = "--defsym {name}={value}"
output       = "-o {path}"
compile_only = ""
dep_file     = ""
target       = ""
sysroot      = ""

[arch_flags]
"x86.linux"      = "--32"

[language.modules]
style = "none"

[linking.gas]
abi        = "c"
compatible = ["c", "cpp"]
linker     = ""
extensions = [".s", ".S"]
