name          = "gcc"
alias         = "g++"
kind          = "compiler"
family        = "gnu"
homepage      = "https://gcc.gnu.org/"

detect       = ["gcc"]
always_flags = ["$(arch == 'x86_64' ? '-m64' : arch == 'x86' ? '-m32' : '')"]

debug = "-g"
lto      = "-flto"
cpu_ext  = "-m{name}"

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
format  = "-fsanitize={values}"
options = ["address", "undefined", "thread", "leak"]

[toolset]
cc    = "$(binary)"
cxx   = "$(binary.replace('gcc', 'g++'))"
ld    = "$(binary.replace('gcc', 'g++'))"
ar    = "ar"
strip = "strip"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-MMD -MF {path}"
target       = ""
sysroot      = "--sysroot={path}"

[optimization]
"0" = "-O0"
"1" = "-O1"
"2" = "-O2"
"3" = "-O3"
"s" = "-Os"
"z" = "-Oz"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra -Wpedantic"
error  = "-Wall -Wextra -Wpedantic -Werror"

[language.std]
"c11" = "-std=c11"
"c17" = "-std=c17"
"c23" = "-std=c23"

[language.modules]
style = "none"

[linking.c]
abi            = "c"
compatible     = ["fortran", "asm"]
compile_binary = "$(binary)"
linker         = ""
extensions     = [".c", ".s", ".S"]
