kind          = "debugger"
name          = "gdb"
[version]
argument = "--version"
regex    = 'GNU gdb[^\d]+(\d+\.\d+)'

[launch]
separator = "--args"

[dap]
binaries    = []
vscode_type = "cppdbg"
mi_mode     = "gdb"

[settings]
tui   = "--tui"
quiet = "-q"
batch = "--batch"
