name          = "gfortran"
kind          = "compiler"
family        = "gnu"
homepage      = "https://gcc.gnu.org/fortran/"

debug = "-g"
lto      = "-flto"
cpu_ext  = ""

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
argument = "-fsanitize={values}"
options = ["address", "undefined"]

[arch_flags]
x86_64 = "-m64"
x86    = "-m32"

[toolset]
ld    = "gfortran"
ar    = "ar"
strip = "strip"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-cpp -MMD -MF {path}"
target       = ""
sysroot      = "--sysroot={path}"

[optimization]
"0" = "-O0"
"1" = "-O1"
"2" = "-O2"
"3" = "-O3"
"s" = "-Os"
"z" = "-Oz"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra"
error  = "-Wall -Wextra -Werror"

[language.std]
"f95"   = "-std=f95"
"f2003" = "-std=f2003"
"f2008" = "-std=f2008"
"f2018" = "-std=f2018"
[linking.fortran]
abi        = "fortran"
compatible = ["c"]
linker     = ""
extensions = [".f90", ".f95", ".f03", ".f08", ".f", ".F90"]
