name          = "gfortran"
kind          = "compiler"
family        = "gnu"
homepage      = "https://gcc.gnu.org/fortran/"

supported_os    = ["linux", "macos", "windows"]

debug    = "-g"
lto      = "-flto"
lto_link = "-flto"
cpu_ext  = "-m{name}"

[version]
argument = "--version"
regex    = '\b(\d+\.\d+\.\d+)\b'

[sanitizer]
argument = "-fsanitize={values}"
options = ["address", "undefined"]

[arch_flags]
x86_64      = "-m64"
x86         = "-m32"

[toolset]
ld     = "gfortran"
ar     = "ar"
ranlib = "ranlib"
strip  = "strip"
nm     = "nm"

[structure]
include_dir  = "-I{path}"
define       = "-D{name}"
define_value = "-D{name}={value}"
output       = "-o {path}"
compile_only = "-c"
dep_file     = "-cpp -MMD -MF {path}"
system_lib   = "-l{name}"
target       = ""
sysroot      = "--sysroot={path}"

[optimization]
"0"    = "-O0"
"1"    = "-O1"
"2"    = "-O2"
"3"    = "-O3"
"g"    = "-Og"
"s"    = "-Os"
"z"    = "-Oz"
"fast" = "-Ofast"

[warnings]
normal = "-Wall"
none   = ""
all    = "-Wall -Wextra"
error  = "-Wall -Wextra -Werror"

[language.std]
"f2003" = "-std=f2003"
"f2008" = "-std=f2008"
"f2018" = "-std=f2018"
"f95"   = "-std=f95"

[language.implicit_none]
enabled  = "-fimplicit-none"
disabled = ""

[language.real_kind]
"32"  = ""
"64"  = "-fdefault-real-8"
"128" = "-fdefault-real-16"

[language.openmp]
enabled  = "-fopenmp"
disabled = ""

[compiler.debug_info]
dwarf4 = "-gdwarf-4"
dwarf5 = "-gdwarf-5"
gdb    = "-ggdb3"
"1"    = "-g1"
"2"    = "-g2"
"3"    = "-g3"

[compiler.lto_mode]
auto      = "-flto=auto"
jobserver = "-flto=jobserver"

[linking.fortran]
abi        = "fortran"
compatible = ["c"]
linker     = ""
extensions = [".f90", ".f95", ".f03", ".f08", ".f", ".F90"]
