kind          = "linter"
name          = "flawfinder"
family        = "flawfinder"
binary        = "flawfinder"
extensions    = [".cpp", ".cc", ".cxx", ".c++", ".c", ".h", ".hpp", ".hxx"]

[header]
version_arg   = "--version"
version_regex = 'Flawfinder version (\d+\.\d+)'

[run]
check = "--error-level=1"
fix   = "--error-level=1"

[settings]
minlevel = "--minlevel={value}"

[values]
minlevel = ["0", "1", "2", "3", "4", "5"]
